[package]
name = "sqlite-jsonschema"
version = "0.1.0-alpha.8"
edition = "2021"

[dependencies]
sqlite-loadable = "0.0.5"
jsonschema = {version="0.16.1", default-features = false}
serde_json = "1.0.87"

[lib]
crate-type=["lib", "staticlib", "cdylib"]